### ISSUE TITLE
The plugin doesn't have the version number

### ISSUE THREAD

**Issue by AmaliaMV** [grails-guides/grails-multi-project-build#7]
When I run the app, the plugin doesn't have the version number

![image](https://user-images.githubusercontent.com/5392638/50405693-47f1dd00-0797-11e9-86f1-4265962d58e8.png)

The jar filename has the same version number that the build.gradle 
![image](https://user-images.githubusercontent.com/5392638/50405704-68219c00-0797-11e9-955a-662d05d7091d.png)

but the grails-plugin.xml said:

```
<plugin name='grailsPlugin' version='unspecified' grailsVersion='3.2.9 &gt; *'>
```

**Comment by graemerocher** [comment]
This would be the case when the app is run in development mode because the JAR is not built instead the classes are put on the class path to support reloading, but once built for production the actual version will be specified.

This is just the way it works currently and since we do not programmatically parse the `build.gradle` (and will not do so due to that being impossible anyway) there is currently no possible way to fix this and it is working as designed.

**Comment by AmaliaMV** [comment]
Thanks @graemerocher for the answer!.

I have just build the war file and have deployed it, but the plugin's version isn't specified any way. 

![screenshot from 2019-01-04 15-39-11](https://user-images.githubusercontent.com/5392638/50704686-ff5bde80-1036-11e9-9986-de10173ab9c7.png)

![screenshot from 2019-01-04 15-33-34](https://user-images.githubusercontent.com/5392638/50704712-0e429100-1037-11e9-936b-a3f7d3862d29.png)

Where should we put the version of our plugin so that it is visible in production?

**Comment by jameskleeh** [comment]
@AmaliaMV The answer is to add a version property to your plugin class

**Comment by AmaliaMV** [comment]
@jameskleeh ,  thanks! .. if I add to the Plugin class, I can see the version now.
